# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: getproxy

on:
  push:
    branches: [ proxy ]
  schedule:
    # * is a special character in YAML so you have to quote this string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.5
    - name: setup env & install getproxy
      run: |
        git config --global user.name "fastbotovitchROSOLL"
        git config --global user.email "fastbotovitch@yandex.ru"
        pip install git
        git clone https://github.com/Cicadadenis/x@master
    - name: run getproxy
      run: |
        cd x/
        python3 Setyp.py
    - name: commit
      run: |
        rm -rf .git
        git init
        git add .
        git commit -m "`env TZ=Asia/Magadan date`"
        git remote add origin https://github.com/fastbotovitchROSOLL/FreeProxy-Anonim-VeryAnonim-.git


    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true


